
version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/pulumiquickstart/
    steps:
      - checkout
      - pulumi/login
      - pulumi/update:
          stack: pulumiquickstart
          working_directory: ~/pulumiquickstart/


